return {
  "AstroNvim/astrocommunity",
  { import = "astrocommunity.bars-and-lines.scope-nvim" },
  { import = "astrocommunity.color.headlines-nvim" },
  { import = "astrocommunity.colorscheme.gruvbox" },
  -- { import = "astrocommunity.colorscheme.gruvbox-baby" },
  -- { import = "astrocommunity.note-taking.neorg" },
  { import = "astrocommunity.motion.nvim-surround" },
  { import = "astrocommunity.pack.bash" },
  -- { import = "astrocommunity.pack.lua" },
  { import = "astrocommunity.pack.terraform" },
  { import = "astrocommunity.pack.rust" },
  { import = "astrocommunity.pack.nix" },
  { import = "astrocommunity.git.octo" },
  -- { import = "astrocommunity.pack.toml" },
  -- { import = "astrocommunity.pack.yaml" },
  -- { import = "astrocommunity.bars-and-lines.heirline-mode-text-statusline" },
}
